### ISSUE TITLE
SDK Issues

### ISSUE THREAD

**Issue by loser007** [line/line-sdk-starter-android-v2#2]
Class not found when unmarshalling: com.linecorp.linesdk.auth.LineAuthenticationConfig
java.lang.ClassNotFoundException: com.linecorp.linesdk.auth.LineAuthenticationConfig

on Samsung occur this

**Comment by loser007** [comment]
line-sdk-4.0.0

**Comment by mrmaakun** [comment]
Hi @loser007 

Could you provide more details about how to reproduce the problem? Were you able to reproduce this in this starter application?

**Comment by loser007** [comment]
yes,line-sdk-4.0.0 on Samsung 4.42 inevitable reproduction,and anonther phone act normally。
line-android-sdk-3.1.21 is Ok

**Comment by loser007** [comment]
03-29 17:03:19.001 3865-4446/? E/DatabaseUtils: Writing exception to parcel
java.lang.SecurityException: Permission Denial: get/set setting for user asks to run as user -2 but is calling from user 0; this requires android.permission.INTERACT_ACROSS_USERS_FULL
at com.android.server.am.ActivityManagerService.handleIncomingUser(ActivityManagerService.java:14799)
at android.app.ActivityManager.handleIncomingUser(ActivityManager.java:2473)
at com.android.providers.settings.SettingsProvider.call(SettingsProvider.java:688)
at android.content.ContentProvider$Transport.call(ContentProvider.java:325)
at android.content.ContentProviderNative.onTransact(ContentProviderNative.java:275)
at android.os.Binder.execTransact(Binder.java:404)
at dalvik.system.NativeStart.run(Native Method)

Class not found when unmarshalling: com.linecorp.linesdk.auth.LineAuthenticationConfig
java.lang.ClassNotFoundException: com.linecorp.linesdk.auth.LineAuthenticationConfig
at java.lang.Class.classForName(Native Method)
at java.lang.Class.forName(Class.java:251)
at java.lang.Class.forName(Class.java:216)
at android.os.Parcel.readParcelableCreator(Parcel.java:2133)
at android.os.Parcel.readParcelable(Parcel.java:2097)
at android.os.Parcel.readValue(Parcel.java:2013)
at android.os.Parcel.readArrayMapInternal(Parcel.java:2314)

**Comment by mrmaakun** [comment]
Hi @loser007 

We released line-sdk-4.0.2 to resolve some issues with Android 4.x. Could you try using the latest version of the SDK?

I found a Samsung 4.4.2 device and tested this starter application using the latest version of the Android SDK (line-sdk-4.0.2) and I could not reproduce the issue.

**Comment by FlorianBergmann** [comment]
I have the same error with line-sdk-4.0.5 on an Samsung device. It happens when a user tries to login using the Line login with the Line App installed but no Account setup in the app. The login screen only shows an endless loading screen.

The expected behavior would be that the user either has to login using the web login or will be prompted to setup an Account inside the Line app. Currently the user is stuck and I can also not react to it inside my own app.

**Comment by mrmaakun** [comment]
Hi @FlorianBergmann

I will have our development team look at this behavior. I will post an update when I get more information.

**Comment by avenhurkatolto** [comment]
I have the same problem as @FlorianBergmann. Also, I may have found a 7.0 issue. Here are my issues:

Issue A: on 7.0, if you have installed Line app but have never opened it, and you try app login from the sample app (or an app that uses the sdk) the Line app flashes for a moment but closing immediately, while getting this error in the background (not in the app, this is a system error, which doesn't appear if you filtering your app messages)
` W/WindowManager: Failed looking up window
                                                java.lang.IllegalArgumentException: Requested window android.view.ViewRootImpl$W@dec492f does not exist
at com.android.server.wm.WindowManagerService.windowForClientLocked(WindowManagerService.java:10302)
at com.android.server.wm.WindowManagerService.windowForClientLocked(WindowManagerService.java:10293)
at com.android.server.wm.WindowManagerService.removeWindow(WindowManagerService.java:2632)
                                                    at com.android.server.wm.Session.remove(Session.java:208)
at android.view.ViewRootImpl.dispatchDetachedFromWindow(ViewRootImpl.java:3676)
                                                    at android.view.ViewRootImpl.doDie(ViewRootImpl.java:6583)
at android.view.ViewRootImpl$ViewRootHandler.handleMessage(ViewRootImpl.java:4082)
                                                    at android.os.Handler.dispatchMessage(Handler.java:102)
                                                    at android.os.Looper.loop(Looper.java:154)
                                                    at android.os.HandlerThread.run(HandlerThread.java:61)
                                                    at com.android.server.ServiceThread.run(ServiceThread.java:46)`

used devices: 
-Vernee thor (7.0)
-Samsung Galaxy S7 (7.0)

steps to reproduce:
1: install Line app from Store, but DON'T open it
2: install sample app, press on "Login with LINE" button

Result: infinite loading with a flash (Line app starts but closes immediately)
Expected result: Line app starts normally

Issue B:@FlorianBergmann's issue (I suppose)
 When you try to login with Line app, but you don't have an account set, you won't get back the intent.

Used devices:
-Vernee thor (7.0)
-Samsung Galaxy S7 (7.0)
-Samsung Galaxy S4 (5.0.1)

Steps to reproduce:

1: install Line app (open, if you have 7.0 device and encountered issue A), but don't log in
2: open your app or the sample app (configured on the Business Center), try to login with Line app
3: Line app opens, log in normally (in my case I used Facebook confirmation if it helps)

Result: Line app stays if it was started by the user, not by another app, by "closing" with back button, the caller app still doesn't get the login intent (resultCode is 0, which equals to Activity.RESULT_CANCELED), after this, if you call Line app login again, you'll get the login intent without any issue

Expected result: either:
-Line app closes and hands back the login intent immediately after successful login or non-recoverable error
-Pressing the back button hands back the correct intent based on the login state

**Comment by tearoom6** [comment]
I had the similar problem described above.

In logcat, LINE app emitted the stack trace like:

```
07-20 15:33:37.209  3699  6731 E Parcel  : Class not found when unmarshalling: com.linecorp.linesdk.auth.LineAuthenticationConfig
07-20 15:33:37.209  3699  6731 E Parcel  : java.lang.ClassNotFoundException: com.linecorp.linesdk.auth.LineAuthenticationConfig
07-20 15:33:37.209  3699  6731 E Parcel  :      at java.lang.Class.classForName(Native Method)
07-20 15:33:37.209  3699  6731 E Parcel  :      at java.lang.Class.forName(Class.java:400)
07-20 15:33:37.209  3699  6731 E Parcel  :      at android.os.Parcel.readParcelableCreator(Parcel.java:2517)
07-20 15:33:37.209  3699  6731 E Parcel  :      at android.os.Parcel.readParcelable(Parcel.java:2471)
07-20 15:33:37.209  3699  6731 E Parcel  :      at android.os.Parcel.readValue(Parcel.java:2374)
07-20 15:33:37.209  3699  6731 E Parcel  :      at android.os.Parcel.readArrayMapInternal(Parcel.java:2727)
07-20 15:33:37.209  3699  6731 E Parcel  :      at android.os.BaseBundle.unparcel(BaseBundle.java:269)
07-20 15:33:37.209  3699  6731 E Parcel  :      at android.os.BaseBundle.getString(BaseBundle.java:992)
07-20 15:33:37.209  3699  6731 E Parcel  :      at android.content.Intent.getStringExtra(Intent.java:6702)
07-20 15:33:37.209  3699  6731 E Parcel  :      at com.android.server.am.ActivityStarter.startActivityLocked(ActivityStarter.java:341)
07-20 15:33:37.209  3699  6731 E Parcel  :      at com.android.server.am.ActivityStarter.startActivityMayWait(ActivityStarter.java:1096)
07-20 15:33:37.209  3699  6731 E Parcel  :      at com.android.server.am.ActivityManagerService.startActivityAsUser(ActivityManagerService.java:5836)
07-20 15:33:37.209  3699  6731 E Parcel  :      at com.android.server.am.ActivityManagerService.startActivity(ActivityManagerService.java:5641)
07-20 15:33:37.209  3699  6731 E Parcel  :      at android.app.ActivityManagerNative.onTransact(ActivityManagerNative.java:176)
07-20 15:33:37.209  3699  6731 E Parcel  :      at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:3611)
07-20 15:33:37.209  3699  6731 E Parcel  :      at android.os.Binder.execTransact(Binder.java:573)
07-20 15:33:37.209  3699  6731 E Parcel  : Caused by: java.lang.ClassNotFoundException: com.linecorp.linesdk.auth.LineAuthenticationConfig
07-20 15:33:37.209  3699  6731 E Parcel  :      at java.lang.Class.classForName(Native Method)
07-20 15:33:37.209  3699  6731 E Parcel  :      at java.lang.BootClassLoader.findClass(ClassLoader.java:1346)
07-20 15:33:37.209  3699  6731 E Parcel  :      at java.lang.BootClassLoader.loadClass(ClassLoader.java:1406)
07-20 15:33:37.209  3699  6731 E Parcel  :      at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
07-20 15:33:37.209  3699  6731 E Parcel  :      ... 16 more
07-20 15:33:37.209  3699  6731 E Parcel  : Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack trace available
07-20 15:33:37.435  3699  7940 E Parcel  : Class not found when unmarshalling: jp.naver.line.android.urlscheme.service.oauth.OAuthWebLoginService$OAuthWebLoginRequest
07-20 15:33:37.435  3699  7940 E Parcel  : java.lang.ClassNotFoundException: jp.naver.line.android.urlscheme.service.oauth.OAuthWebLoginService$OAuthWebLoginRequest
07-20 15:33:37.435  3699  7940 E Parcel  :      at java.lang.Class.classForName(Native Method)
07-20 15:33:37.435  3699  7940 E Parcel  :      at java.lang.Class.forName(Class.java:400)
07-20 15:33:37.435  3699  7940 E Parcel  :      at android.os.Parcel.readParcelableCreator(Parcel.java:2517)
07-20 15:33:37.435  3699  7940 E Parcel  :      at android.os.Parcel.readParcelable(Parcel.java:2471)
07-20 15:33:37.435  3699  7940 E Parcel  :      at android.os.Parcel.readValue(Parcel.java:2374)
07-20 15:33:37.435  3699  7940 E Parcel  :      at android.os.Parcel.readArrayMapInternal(Parcel.java:2727)
07-20 15:33:37.435  3699  7940 E Parcel  :      at android.os.BaseBundle.unparcel(BaseBundle.java:269)
07-20 15:33:37.435  3699  7940 E Parcel  :      at android.os.BaseBundle.getString(BaseBundle.java:992)
07-20 15:33:37.435  3699  7940 E Parcel  :      at android.content.Intent.getStringExtra(Intent.java:6702)
07-20 15:33:37.435  3699  7940 E Parcel  :      at com.android.server.am.ActivityStarter.startActivityLocked(ActivityStarter.java:341)
07-20 15:33:37.435  3699  7940 E Parcel  :      at com.android.server.am.ActivityStarter.startActivityMayWait(ActivityStarter.java:1096)
07-20 15:33:37.435  3699  7940 E Parcel  :      at com.android.server.am.ActivityManagerService.startActivityAsUser(ActivityManagerService.java:5836)
07-20 15:33:37.435  3699  7940 E Parcel  :      at com.android.server.am.ActivityManagerService.startActivity(ActivityManagerService.java:5641)
07-20 15:33:37.435  3699  7940 E Parcel  :      at android.app.ActivityManagerNative.onTransact(ActivityManagerNative.java:176)
07-20 15:33:37.435  3699  7940 E Parcel  :      at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:3611)
07-20 15:33:37.435  3699  7940 E Parcel  :      at android.os.Binder.execTransact(Binder.java:573)
07-20 15:33:37.435  3699  7940 E Parcel  : Caused by: java.lang.ClassNotFoundException: jp.naver.line.android.urlscheme.service.oauth.OAuthWebLoginService$OAuthWebLoginRequest
07-20 15:33:37.435  3699  7940 E Parcel  :      at java.lang.Class.classForName(Native Method)
07-20 15:33:37.435  3699  7940 E Parcel  :      at java.lang.BootClassLoader.findClass(ClassLoader.java:1346)
07-20 15:33:37.435  3699  7940 E Parcel  :      at java.lang.BootClassLoader.loadClass(ClassLoader.java:1406)
07-20 15:33:37.435  3699  7940 E Parcel  :      at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
07-20 15:33:37.435  3699  7940 E Parcel  :      ... 16 more
07-20 15:33:37.435  3699  7940 E Parcel  : Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack trace available
```

Finally i can solve the problem by fixing [Android Package Name] in [Technical configuration] of the channel's web console.
If that's the case, it might be good to check that :)

**Comment by strength0179** [comment]
still happening.

Device：
Samsung J5 (2015 or 2016??)

IDE：
Eclipse Oxygen

05-11 13:54:30.631: E/Parcel(1549): Class not found when unmarshalling: com.linecorp.linesdk.auth.LineAuthenticationConfig
05-11 13:54:30.631: E/Parcel(1549): java.lang.ClassNotFoundException: com.linecorp.linesdk.auth.LineAuthenticationConfig
05-11 13:54:30.631: E/Parcel(1549): 	at java.lang.Class.classForName(Native Method)
05-11 13:54:30.631: E/Parcel(1549): 	at java.lang.Class.forName(Class.java:324)
05-11 13:54:30.631: E/Parcel(1549): 	at android.os.Parcel.readParcelableCreator(Parcel.java:2404)
05-11 13:54:30.631: E/Parcel(1549): 	at android.os.Parcel.readParcelable(Parcel.java:2358)
05-11 13:54:30.631: E/Parcel(1549): 	at android.os.Parcel.readValue(Parcel.java:2264)
05-11 13:54:30.631: E/Parcel(1549): 	at android.os.Parcel.readArrayMapInternal(Parcel.java:2614)
05-11 13:54:30.631: E/Parcel(1549): 	at android.os.BaseBundle.unparcel(BaseBundle.java:221)
05-11 13:54:30.631: E/Parcel(1549): 	at android.os.BaseBundle.getString(BaseBundle.java:920)
05-11 13:54:30.631: E/Parcel(1549): 	at android.content.Intent.getStringExtra(Intent.java:6195)
05-11 13:54:30.631: E/Parcel(1549): 	at com.android.server.am.ActivityStackSupervisor.startActivityLocked(ActivityStackSupervisor.java:2726)
05-11 13:54:30.631: E/Parcel(1549): 	at com.android.server.am.ActivityStackSupervisor.startActivityMayWait(ActivityStackSupervisor.java:2193)
05-11 13:54:30.631: E/Parcel(1549): 	at com.android.server.am.ActivityManagerService.startActivityAsUser(ActivityManagerService.java:6378)
05-11 13:54:30.631: E/Parcel(1549): 	at com.android.server.am.ActivityManagerService.startActivity(ActivityManagerService.java:6149)
05-11 13:54:30.631: E/Parcel(1549): 	at android.app.ActivityManagerNative.onTransact(ActivityManagerNative.java:170)
05-11 13:54:30.631: E/Parcel(1549): 	at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:4009)
05-11 13:54:30.631: E/Parcel(1549): 	at android.os.Binder.execTransact(Binder.java:453)
05-11 13:54:30.631: E/Parcel(1549): Caused by: java.lang.ClassNotFoundException: com.linecorp.linesdk.auth.LineAuthenticationConfig
05-11 13:54:30.631: E/Parcel(1549): 	at java.lang.Class.classForName(Native Method)
05-11 13:54:30.631: E/Parcel(1549): 	at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
05-11 13:54:30.631: E/Parcel(1549): 	at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
05-11 13:54:30.631: E/Parcel(1549): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
05-11 13:54:30.631: E/Parcel(1549): 	... 16 more
05-11 13:54:30.631: E/Parcel(1549): Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack trace available


How I solve it？


        <activity
            android:name="com.linecorp.linesdk.auth.internal.LineAuthenticationActivity"
            android:configChanges="orientation|screenSize|keyboardHidden"
            android:exported="true"
            android:launchMode="singleTop"
            android:theme="@style/LineSdk_AuthenticationActivity" />
        <activity
            android:name="com.linecorp.linesdk.auth.internal.LineAuthenticationCallbackActivity"
            android:configChanges="orientation|screenSize|keyboardHidden"
            android:exported="true" >
            <intent-filter>
                <action android:name="android.intent.action.VIEW" />

                <category android:name="android.intent.category.DEFAULT" />
                <category android:name="android.intent.category.BROWSABLE" />

                <data android:scheme="lineauth" />
            </intent-filter>
        </activity>


Copy this and paste on my app's AndroidManifest.xml. Then it works.

**Comment by xiaoyepadzhang** [comment]
@mrmaakun this problem occur on Samsung S8+, Android version: 8.0.0.
Can you fix this problem or How can I fix this ClassNotFoundException?

**Comment by strength0179** [comment]
Sorry. It was a project I was working with  a few month ago. So I can't
recall the detail. Can you give me more information？

2018-07-23 17:40 GMT+08:00 xiaoyepadzhang <notifications@github.com>:

**Comment by xiaoyepadzhang** [comment]
@strength0179 Hi,
    I run your demo with the two button called 'Login with LINE'  and 'Browser Login'. If the LINE App never open and I click the 'Login with LINE', the demo will make a loading progress in the middle with half a second and finish with no change. I find that it had run into onActivityResult and result.getResponseCode() == CANCEL.
You can also see all the description  in this issue. We are had got the same problem, And it occur on the same Brand Samsung. Our team have two Samsung device and had the same problem.

This is my device info:
    Device: Samsung S8+ 
    Model: SM-G9550
    Android Version: 8.0.0
    Samsung Experience Version: 9.0

Show the log:

`07-23 18:23:55.197 3313-6277/? E/Parcel: Class not found when unmarshalling: com.linecorp.linesdk.auth.LineAuthenticationConfig
    java.lang.ClassNotFoundException: com.linecorp.linesdk.auth.LineAuthenticationConfig
        at java.lang.Class.classForName(Native Method)
        at java.lang.Class.forName(Class.java:453)
        at android.os.Parcel.readParcelableCreator(Parcel.java:2835)
        at android.os.Parcel.readParcelable(Parcel.java:2789)
        at android.os.Parcel.readValue(Parcel.java:2692)
        at android.os.Parcel.readArrayMapInternal(Parcel.java:3059)
        at android.os.BaseBundle.unparcel(BaseBundle.java:257)
        at android.os.BaseBundle.getString(BaseBundle.java:1086)
        at android.content.Intent.getStringExtra(Intent.java:7706)
        at com.android.server.am.ActivityStarter.startActivity(ActivityStarter.java:459)
        at com.android.server.am.ActivityStarter.startActivityLocked(ActivityStarter.java:410)
        at com.android.server.am.ActivityStarter.startActivityMayWait(ActivityStarter.java:1277)
        at com.android.server.am.ActivityManagerService.startActivityAsUser(ActivityManagerService.java:6014)
        at com.android.server.am.ActivityManagerService.startActivity(ActivityManagerService.java:5867)
        at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:121)
        at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:3844)
        at android.os.Binder.execTransact(Binder.java:682)
     Caused by: java.lang.ClassNotFoundException: com.linecorp.linesdk.auth.LineAuthenticationConfig
        at java.lang.Class.classForName(Native Method)
        at java.lang.BootClassLoader.findClass(ClassLoader.java:1355)
        at java.lang.BootClassLoader.loadClass(ClassLoader.java:1415)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at java.lang.Class.classForName(Native Method) 
        at java.lang.Class.forName(Class.java:453) 
        at android.os.Parcel.readParcelableCreator(Parcel.java:2835) 
        at android.os.Parcel.readParcelable(Parcel.java:2789) 
        at android.os.Parcel.readValue(Parcel.java:2692) 
        at android.os.Parcel.readArrayMapInternal(Parcel.java:3059) 
        at android.os.BaseBundle.unparcel(BaseBundle.java:257) 
        at android.os.BaseBundle.getString(BaseBundle.java:1086) 
        at android.content.Intent.getStringExtra(Intent.java:7706) 
        at com.android.server.am.ActivityStarter.startActivity(ActivityStarter.java:459) 
        at com.android.server.am.ActivityStarter.startActivityLocked(ActivityStarter.java:410) 
        at com.android.server.am.ActivityStarter.startActivityMayWait(ActivityStarter.java:1277) 
        at com.android.server.am.ActivityManagerService.startActivityAsUser(ActivityManagerService.java:6014) 
        at com.android.server.am.ActivityManagerService.startActivity(ActivityManagerService.java:5867) 
        at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:121) 
        at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:3844) 
        at android.os.Binder.execTransact(Binder.java:682) 
     Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack trace available
07-23 18:23:55.197 3313-6277/? W/Bundle: Failed to parse Bundle, but defusing quietly
    android.os.BadParcelableException: ClassNotFoundException when unmarshalling: com.linecorp.linesdk.auth.LineAuthenticationConfig
        at android.os.Parcel.readParcelableCreator(Parcel.java:2863)
        at android.os.Parcel.readParcelable(Parcel.java:2789)
        at android.os.Parcel.readValue(Parcel.java:2692)
        at android.os.Parcel.readArrayMapInternal(Parcel.java:3059)
        at android.os.BaseBundle.unparcel(BaseBundle.java:257)
        at android.os.BaseBundle.getString(BaseBundle.java:1086)
        at android.content.Intent.getStringExtra(Intent.java:7706)
        at com.android.server.am.ActivityStarter.startActivity(ActivityStarter.java:459)
        at com.android.server.am.ActivityStarter.startActivityLocked(ActivityStarter.java:410)
        at com.android.server.am.ActivityStarter.startActivityMayWait(ActivityStarter.java:1277)
        at com.android.server.am.ActivityManagerService.startActivityAsUser(ActivityManagerService.java:6014)
        at com.android.server.am.ActivityManagerService.startActivity(ActivityManagerService.java:5867)
        at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:121)
        at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:3844)
        at android.os.Binder.execTransact(Binder.java:682)`

**Comment by xiaoyepadzhang** [comment]
@strength0179 
By the way, if the LINE app is running in the background, It will not occur the problem.

**Comment by strength0179** [comment]
Two suggection:

1.
Obviously, you got a respond from Line Server.
But the respond tell your local SDK that the request of login (or anything
you send) is canceled.

Your Java code should be ok. But the login-setting you use is wrong. (Yeah.
It is possible. The API is a mistake that lead you to fail.)

2.
It's been a few month since I work with Line SDK, so there must be
something changed.
But you say it works fine in the background....

You probably miss a Activity to set in your AndroidManefest. It happen to
me once. You can take a shot on that.

If my suggestion wouldn't help you, you might need someone who is better in
this.


Good luck.




2018-07-23 18:27 GMT+08:00 xiaoyepadzhang <notifications@github.com>:
