### ISSUE TITLE
LineAuthenticationActivity NullPointerException

### ISSUE THREAD

**Issue by SuperTizzyGod** [line/line-sdk-starter-android-v2#20]
Hi,this Exception happen in Galaxy S7 ,android 7.0 rom:
any advices?
![image](https://user-images.githubusercontent.com/31981086/32761471-720c0172-c92e-11e7-87ba-a661047ee5b8.png)

**Comment by SuperTizzyGod** [comment]
Detail info is:
Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{fm.castbox.audiobook.radio.podcast/com.linecorp.linesdk.auth.internal.LineAuthenticationActivity}: java.lang.NullPointerException: Attempt to read from field 'int com.linecorp.linesdk.auth.internal.d.d' on a null object reference
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2927)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2988)
       at android.app.ActivityThread.-wrap14(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1631)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6682)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)
Caused by java.lang.NullPointerException: Attempt to read from field 'int com.linecorp.linesdk.auth.internal.d.d' on a null object reference
       at com.linecorp.linesdk.auth.internal.LineAuthenticationActivity.a(SourceFile:11062)
       at com.linecorp.linesdk.auth.internal.LineAuthenticationActivity.onCreate(SourceFile:71)
       at android.app.Activity.performCreate(Activity.java:6942)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1126)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2880)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2988)
       at android.app.ActivityThread.-wrap14(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1631)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6682)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)

**Comment by lekyzhang** [comment]
Saw the same exception in our app. Please fix this.

**Comment by HirotoIchinose** [comment]
Saw the same exception in our app. Please fix this.

**Comment by koichi-ozaki** [comment]
Saw the same exception in our app. Please fix this.
