### ISSUE TITLE
login fail ?

### ISSUE THREAD

**Issue by acter** [line/line-sdk-starter-android-v2#27]
tools:eclipse

linesdk :4.0.8

05-28 18:32:22.396 22764 22764 E AndroidRuntime: java.lang.NoClassDefFoundError: Failed resolution of: Landroid/support/customtabs/CustomTabsIntent$Builder;
05-28 18:32:22.396 22764 22764 E AndroidRuntime: 	at com.linecorp.linesdk.auth.internal.c$c.onPostExecute(SourceFile:12180)
05-28 18:32:22.396 22764 22764 E AndroidRuntime: 	at android.os.AsyncTask.finish(AsyncTask.java:667)
05-28 18:32:22.396 22764 22764 E AndroidRuntime: 	at android.os.AsyncTask.-wrap1(AsyncTask.java)
05-28 18:32:22.396 22764 22764 E AndroidRuntime: 	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:684)
05-28 18:32:22.396 22764 22764 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)
05-28 18:32:22.396 22764 22764 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:159)
05-28 18:32:22.396 22764 22764 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6345)
05-28 18:32:22.396 22764 22764 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
05-28 18:32:22.396 22764 22764 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1096)
05-28 18:32:22.396 22764 22764 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:883)
05-28 18:32:22.396 22764 22764 E AndroidRuntime: Caused by: java.lang.ClassNotFoundExc
05-28 18:32:22.397 22764 22798 I MID     : read mid from Settings.System
05-28 18:32:22.403  1376  2335 W ActivityManager:   Force finishing activity com.xxxx.test/com.linecorp.linesdk.auth.internal.LineAuthenticationActivity, mTaskHistory size = 30

**Comment by wangbax** [comment]
`implementation 'androidx.browser:browser:1.3.0'`

https://developer.android.com/jetpack/androidx/releases/browser
